---
# This file contains the configuration for a certificate client

api:
    basedir: /people/r3boot/git/pki/workspace
    url: http://localhost:4392/autosign
    token: fc31cac6af19bf001816060cdb6f9070240dcc19387f944a85545806e76a815b

certs:
    bits: 4096
    hash: sha512
    country: NL
    province: Utrecht
    city: Amersfoort
    organization: AS65342
    unit: Autosign
