---
# This file contains the configuration for the AS65342 pki scripting
# infrastructure

common:
    name: as65342
    workspace: /etc/pki
    baseurl: http://pki.as65342.net
    ocspurl: http://oscp.as65342.net
    country: NL
    province: Utrecht
    city: Amersfoort
    organization: AS65342
    unit: PKI services
    days: 3652

crypto:
    algo: rsa
    bits: 4096
    hash: sha512

root:
    cn: AS65342 Root CA

intermediary:
    cn: AS65342 Intermediary CA

autosign:
    cn: AS65342 Infrastructure CA
    unit: Autosign
    days: 365
