---
# This file contains the configuration for the Test pki scripting
# infrastructure

common:
    name: test
    workspace: ./workspace
    baseurl: http://pki.example.com
    ocspurl: http://oscp.example.com
    country: NL
    province: Province
    city: City
    organization: Test
    unit: Organizational Unit
    days: 3652

crypto:
    algo: rsa
    bits: 4096
    hash: sha512

root:
    cn: Test Root CA

intermediary:
    cn: Test Intermediary CA

autosign:
    cn: Test Infrastructure CA
    unit: Autosign
    days: 365
