#!/usr/bin/env python2

import os
import sys
import jinja2
sys.path.append('.')

from pki.logging    import *
from pki            import jsoncfg

__appname__ = 'AS65342 pki'
__version__ = 0.1

valid_operations = [
    'initca',
]

if __name__ == '__main__':
    if len(sys.argv) < 2 or sys.argv[1] in ['-h', '-H', 'help']:
        print('Usage: {0} <operation> [<parameter>,...]'.format(
            os.path.basename(sys.argv[0])))
        print('\nWhere <operation> is one of the following:')
        print('')
        sys.exit(1)
    appdir = os.path.dirname(os.path.abspath(sys.argv[0]))
    appdir = os.path.dirname(appdir)
    os.umask(022)

    operation = sys.argv[1]
    if operation not in valid_operations:
        error('{0} is an invalid operation'.format(operation))

    if operation == 'initca':
        if len(sys.argv) != 3:
            error('Usage: {0} {1} <json file containing parameters>'.format(
                os.path.basename(sys.argv[0]), sys.argv[1]))
        if not os.path.exists(sys.argv[2]):
            error('{0} does not exist'.format(sys.argv[2]))
        config = jsoncfg.load_config(sys.argv[2])

        if 'basedir' not in config:
            info('Using CWD as the basedir for the CA')
            config['basedir'] = '.'
        info('Using {0} as the basedir for the CA'.format(config['basedir']))

        cfgdir = '{0}/cfg'.format(config['basedir'])
        if not os.path.exists(cfgdir):
            info('Setting up configuration directory')
            os.mkdir(cfgdir)

        info('Installing {0} configuration file'.format(config['name']))
        src_cfgfile = '{0}/config/root.cfg.j2'.format(appdir)
        cfgfile = '{0}/cfg/{1}-root.cfg'.format(config['basedir'], config['name'])
        if not os.path.exists(src_cfgfile):
            error('{0} does not exist'.format(src_cfgfile))
        src_cfg = open(src_cfgfile, 'r').read()
        template = jinja2.Template(src_cfg)
        cfgfile_data = template.render(config)
        open(cfgfile, 'w').write(cfgfile_data)

        info('Setup CA directories'.format(config['name']))
        ca_dir = '{0}/ca'.format(config['basedir'])
        if os.path.exists(ca_dir):
            error('{0} already exists'.format(ca_dir))
        os.mkdir(ca_dir)
        os.mkdir('{0}/certs'.format(ca_dir))
        os.mkdir('{0}/private'.format(ca_dir))
        os.mkdir('{0}/db'.format(ca_dir))
        os.mkdir('{0}/certs'.format(config['basedir']))
        os.mkdir('{0}/private'.format(config['basedir']))
        os.mkdir('{0}/db'.format(config['basedir']))

        info('Initialize {{name}}-root database')
        db_dir = '{0}/ca/db'.format(config['basedir'])
        db = '{0}/{1}-root.db'.format(db_dir, config['name'])
        db_attr = '{0}.attr'.format(db)
        db_serial = '{0}/ca/db/{{1}}.crt.srl'.format()
