#!/usr/bin/env python2

import os
import sys
import jinja2
import yaml

sys.path.append('.')

from pki.logging    import *
from pki            import jsoncfg
from pki            import openssl

__appname__ = 'AS65342 pki'
__version__ = 0.1

valid_operations = [
    'initca',
]


if __name__ == '__main__':
    if len(sys.argv) < 2 or sys.argv[1] in ['-h', '-H', 'help']:
        print('Usage: {0} <operation> [<parameter>,...]'.format(
            os.path.basename(sys.argv[0])))
        print('\nWhere <operation> is one of the following:')
        print('')
        sys.exit(1)
    appdir = os.path.dirname(os.path.abspath(sys.argv[0]))
    appdir = os.path.dirname(appdir)
    os.umask(022)

    # Reopen stdout and stderr as unbuffered
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
    sys.stderr = os.fdopen(sys.stderr.fileno(), 'w', 0)

    cfg_file = '{0}/config/pki.yml'.format(appdir)
    if not os.path.exists(cfg_file):
        error('Cannot find {0}'.format(cfg_file))
    raw_cfg = open(cfg_file, 'r').read()
    config = yaml.load(raw_cfg)
    config['appdir'] = appdir

    operation = sys.argv[1]
    if operation not in valid_operations:
        error('{0} is an invalid operation'.format(operation))

    if operation == 'initca':
        if 'basedir' not in config['root']:
            info('Using CWD as the basedir for the CA')
            config['root']['basedir'] = '.'
        info('Using {0} as the basedir for the CA'.format(config['root']['basedir']))

        root = openssl.RootCA(config, 'as65342-root')
        root.setup()
        root.initca()
        root.updatecrl()
