#!/usr/bin/env python2

import os
import sys
import jinja2
import yaml

sys.path.append('.')

from pki.logging    import *
from pki            import jsoncfg
from pki            import openssl
from pki            import service

__appname__ = 'AS65342 pki api service'
__version__ = 0.1


if __name__ == '__main__':
    appdir = os.path.dirname(os.path.abspath(sys.argv[0]))
    appdir = os.path.dirname(appdir)
    cfg_file = cfg_file = '{0}/config/pki.yml'.format(appdir)
    os.umask(022)

    if not os.path.exists(cfg_file):
        error('Cannot find {0}'.format(cfg_file))
    raw_cfg = open(cfg_file, 'r').read()
    config = yaml.load(raw_cfg)
    config['appdir'] = appdir

    service.ca = openssl.AutosignCA(config, name='as65342-servers-autosign')
    service.config = config
    service.run(host='localhost', port=4392)
